// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "goa-erp": company Resource Client
//
// Command:
// $ goagen
// --design=goa-erp/design
// --out=$(GOPATH)\src\goa-erp
// --version=v1.3.0

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ListCompanyPath computes a request path to the list action of company.
func ListCompanyPath() string {

	return fmt.Sprintf("/goa-erp/company")
}

// list all companys
func (c *Client) ListCompany(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListCompanyRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListCompanyRequest create the request corresponding to the list action endpoint of the company resource.
func (c *Client) NewListCompanyRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
