// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "goa-erp": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=goa-erp/design
// --out=$(GOPATH)\src\goa-erp
// --version=v1.3.0

package app
